name: libras_imagery_guide
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.4.4
  collection: ^1.18.0
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  pdfrx: ^1.0.101
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.3.1
  video_player: ^2.9.3
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/prototype/
    - assets/roadmaps/industrial_revolution/images/
    - assets/roadmaps/industrial_revolution/videos/
    - assets/docs/Guia_Prático_para_o_Desenvolvimento_de_Roteiros_Imagéticos_Sinalizados.pdf

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
          weight: 900
